### ISSUE TITLE
[Bug]: Getting "TextToVideoSynthesis.infer() takes from 6 to 11 positional arguments but 12 were given"

### ISSUE THREAD

**Issue by oliverban** [deforum-art/sd-webui-modelscope-text2video#28]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits of both this extension and the webui

### Are you using the latest version of the extension?

- [X] I have the modelscope text2video extension updated to the lastest version and I still have the issue.

### What happened?

Wrote "A girl on a swing" in the prompt, kept everything default. I have the models and config under the specified path in "How to install..." tab. When I clicked generate, something started happening, my console started putting out info but stopped at:

Starting text2video
Exception occured
TextToVideoSynthesis.infer() takes from 6 to 11 positional arguments but 12 were given

And then it does not work and nothing is being generated in the bg.

### Steps to reproduce the problem

1. Go to Modelscope text2video tab (latest A1111 commit and latest MS commit)
2. Write "A girl on a swing" in prompt
3. Click Generate
4. Get the error and move on with your life.

### What should have happened?

It should have generated some kind of images/frames/video.

### WebUI and Deforum extension Commit IDs

webui commit id - Commit hash: a9fed7c364061ae6efb37f797b6b522cb3cf7aa2
txt2vid commit id - Git commit: a1aa3289 (Tue Mar 21 10:54:55 2023)

### What GPU were you using for launching?

3090 24gb vram

### Settings

All default.

### Console logs

```Shell
https://pastebin.com/41Ld1b9r
```

**Comment by 2PeteShakur** [comment]
thx, this fixed it, i was able to use latest text2video model and just deleted cache.json as that was the only file I had. [GPU: 3090].
