### ISSUE TITLE
[Feature request] Add video2video mode (with in-painting and outpainting analogues for making vid from keyframes and AI-continuing vids)

### ISSUE THREAD

**Issue by kabachuha** [deforum-art/sd-webui-modelscope-text2video#4]
Just like stable diffusion is transforming one picture into another one (or noise, if the input is not specified), this model is theoretically capable of transforming a video into another video, using text hints if we initialize the latents with the input video frames

https://github.com/deforum-art/sd-webui-modelscope-text2video/blob/857594d61ea776794296ffa6d256bf93eaa7fcd2/scripts/t2v_pipeline.py#L153

---

The proposed scheme (like img2img, but to videos)

- [ ] Prepare input videos for the input mode (rescaling, cutting to the input length)
- [x] Encode videos to the latent representation by running the VAE
- [x] Configure the DDIM scheduler to use Denoising strength 
- [x] Pass the latents to the pipeline and test it 
- [ ] Bonus: In-framing —pass an input video, add a few keyframes, mask them, fill the rest with latent noise or keep the original, vid2vid diffuse not masked area. Just like in-painting, but for vid2vid
- [ ] Bonus 2: Video continuation — extending the vid with latent noise frames and moving a 'window' making the aforementioned 'in-framing', thus allowing the video to extend beyond vram bounds, but losing some of its temporal coherence

**Comment by Pythonpa** [comment]
> 

Does adding this line of code allow us to go from video to video?

**Comment by kabachuha** [comment]
This line of code points only to that we can replace latents with the video to process encoded via VAE. So it will require one more extra step

**Comment by kabachuha** [comment]
PR adding denoising strength

https://github.com/deforum-art/sd-webui-modelscope-text2video/pull/34

**Comment by nagolinc** [comment]
WIP

https://github.com/deforum-art/sd-webui-modelscope-text2video/pull/37

If anyone knows how to fix it so the results don't look all washed out, that would be super helpful.

**Comment by Apatiste** [comment]
Can we get a Controlnet Pose video 2 video ? 

Basically analyzing the frames poses of the character with the open pose model, saving these Controlnet pictures, loading them back with the controlnet plugin on and the openpose model off, rendering the rest of the vid 2 vid 

the controlnet frames check needs to be done sequentially, to limit the Vram usage

**Comment by kabachuha** [comment]
@Apatiste sounds like a good idea for the future [Deforum](https://github.com/deforum-art/deforum-for-automatic1111-webui)/text2vid integration, since Deforum already has ControlNet support

**Comment by nagolinc** [comment]
I have inpainting working!

Github is acting up atm but I will push a branch as soon as I can.

<img width="928" alt="inpainting_Screenshot 2023-03-27 091243" src="https://user-images.githubusercontent.com/7775917/227947990-b6d90830-157a-4dc2-a24b-5d152b9ef674.png">


![00128-395674870-cute redhead standing in a  field of wheat, freckles, realistic skin texture](https://user-images.githubusercontent.com/7775917/227947819-c88d1489-8893-4acc-b8ec-9fbef5bcd78b.png)

https://user-images.githubusercontent.com/7775917/227947785-8d1cbc9a-005d-46ba-8e01-3d2c0831314c.mp4

**Comment by nagolinc** [comment]
I have inpainting working!

Github is acting up atm but I will push a branch as soon as I can.

<img width="928" alt="inpainting_Screenshot 2023-03-27 091243" src="https://user-images.githubusercontent.com/7775917/227947990-b6d90830-157a-4dc2-a24b-5d152b9ef674.png">


![00128-395674870-cute redhead standing in a  field of wheat, freckles, realistic skin texture](https://user-images.githubusercontent.com/7775917/227947819-c88d1489-8893-4acc-b8ec-9fbef5bcd78b.png)

https://user-images.githubusercontent.com/7775917/227947785-8d1cbc9a-005d-46ba-8e01-3d2c0831314c.mp4
