### ISSUE TITLE
[Feature Request]: Set the seed manually before generating a video

### ISSUE THREAD

**Issue by volotat** [deforum-art/sd-webui-modelscope-text2video#45]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### What would your feature do ?

As described in the title, simply setting the seed before generating a video to be able to reproduce it and generate multiple versions of the same video by slightly changing the prompt while keeping the seed the same. It greatly helps to 'stitch' videos together into a longer one.

### Proposed workflow

1. Go to ui to the 'seed' input  
2. Set the seed -1 for a random one or specify it manually. The same as with all other SD generations.

**Comment by kabachuha** [comment]
Already done in https://github.com/deforum-art/sd-webui-modelscope-text2video/pull/43

Please, update your plugin to the latest version
