### ISSUE TITLE
[Bug]: Exception occured [Errno 2] No such file or directory

### ISSUE THREAD

**Issue by ameen-roayan** [deforum-art/sd-webui-modelscope-text2video#49]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits of both this extension and the webui

### Are you using the latest version of the extension?

- [X] I have the modelscope text2video extension updated to the lastest version and I still have the issue.

### What happened?

I have placed the files in the correct folder but it is not able to read them and i noticed that there is a bit of an odd formatting

Git commit: 092aa423 (Wed Mar 22 19:28:16 2023)
Starting text2video
Pipeline setup
Exception occured
[Errno 2] No such file or directory: 'E:\\Automatic1111\\stable-diffusion-webui\\models/ModelScope/t2v/configuration.json'

the files are in E:\Automatic1111\stable-diffusion-webui\models\Stable-diffusion\ModelScope\t2v not sure what is going on 

### Steps to reproduce the problem

1. download the files
2. place them in the folder

### WebUI and Deforum extension Commit IDs

webui commit id - 
txt2vid commit id -

### What GPU were you using for launching?

3090ti

### On which platform are you launching the webui backend with the extension?

Local PC setup (Windows)

### Settings

Git commit: 092aa423 (Wed Mar 22 19:28:16 2023)
Starting text2video
Pipeline setup
Exception occured
[Errno 2] No such file or directory: 'E:\\Automatic1111\\stable-diffusion-webui\\models/ModelScope/t2v/configuration.json'

### Console logs

```Shell
Git commit: 092aa423 (Wed Mar 22 19:28:16 2023)
Starting text2video
Pipeline setup
Exception occured
[Errno 2] No such file or directory: 'E:\\Automatic1111\\stable-diffusion-webui\\models/ModelScope/t2v/configuration.json'
```

**Comment by ameen-roayan** [comment]
silly me placed it in the wrong folder X_x

**Comment by Joeyd348039** [comment]
> silly me placed it in the wrong folder X_x

What was the folder setup that made it work for you? I've tried a few of them and get that same error.
