### ISSUE TITLE
[Bug]: cannot import name 'get_quick_vid_info'

### ISSUE THREAD

**Issue by Pavankunchala** [deforum-art/sd-webui-modelscope-text2video#51]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits of both this extension and the webui

### Are you using the latest version of the extension?

- [X] I have the modelscope text2video extension updated to the lastest version and I still have the issue.

### What happened?

I am getting this error when I am trying to install the latest version ImportError: cannot import name 'get_quick_vid_info' from 'scripts.video_audio_utils' (C:\Users\pavan\Desktop\Projects\Deep-Learning\webui\extensions\sd-webui-modelscope-text2video\scripts\video_audio_utils.py)

### Steps to reproduce the problem

1. Go to .... 
2. Press ....
3. ...
Install the latest version and  try to run it 

### WebUI and Deforum extension Commit IDs

webui commit id - b1b8b78
txt2vid commit id -

### What GPU were you using for launching?

Rtx 3080 16GB

### On which platform are you launching the webui backend with the extension?

Local PC setup (Windows)

### Settings

No changes to the default settings 

### Console logs

```Shell
Traceback (most recent call last):
  File "C:\Users\pavan\Desktop\Projects\Deep-Learning\webui\modules\scripts.py", line 248, in load_scripts
    script_module = script_loading.load_module(scriptfile.path)
  File "C:\Users\pavan\Desktop\Projects\Deep-Learning\webui\modules\script_loading.py", line 11, in load_module
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\Users\pavan\Desktop\Projects\Deep-Learning\webui\extensions\sd-webui-modelscope-text2video\scripts\modelscope-text2vid.py", line 22, in <module>        
    from scripts.video_audio_utils import ffmpeg_stitch_video, find_ffmpeg_binary, get_quick_vid_info, vid2frames, duplicate_pngs_from_folder, clean_folder_name   
ImportError: cannot import name 'get_quick_vid_info' from 'scripts.video_audio_utils' (C:\Users\pavan\Desktop\Projects\Deep-Learning\webui\extensions\sd-webui-modelscope-text2video\scripts\video_audio_utils.py)
```

**Comment by kabachuha** [comment]
Weird, I checked code and it imports the function correctly (see github tree if you want to). Make sure, your extension updated correctly: try removing it completely and reinstalling from the repo
