### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by GrishDaProgrammer** [deforum-art/sd-webui-modelscope-text2video#78]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits of both this extension and the webui

### Are you using the latest version of the extension?

- [X] I have the modelscope text2video extension updated to the lastest version and I still have the issue.

### What happened?

All txt2img generations resulting in:

Exception occurred: argument of type 'NoneType' is not iterable

I have triple checked the installation instructions and re-downloaded the models, in an attempt to prevent simple oversight.

### Steps to reproduce the problem

1. Click Generate using following settings (or any other combination of settings that I have tried)

![image](https://user-images.githubusercontent.com/116243185/228084285-0228876a-d09f-438f-b016-b3657aa76f5a.png)

2. Pipeline launches successfully.
3. DDIM sampling tensor(1) completes sucessfully.
4. Following Fault Occurs

ModelScope text2video extension for auto1111 webui
Git commit: c8335de9 (Mon Mar 27 19:49:45 2023)
Starting text2video
Pipeline setup
config namespace(framework='pytorch', task='text-to-video-synthesis', model={'type': 'latent-text-to-video-synthesis', 'model_args': {'ckpt_clip': 'open_clip_pytorch_model.bin', 'ckpt_unet': 'text2video_pytorch_model.pth', 'ckpt_autoencoder': 'VQGAN_autoencoder.pth', 'max_frames': 16, 'tiny_gpu': 1}, 'model_cfg': {'unet_in_dim': 4, 'unet_dim': 320, 'unet_y_dim': 768, 'unet_context_dim': 1024, 'unet_out_dim': 4, 'unet_dim_mult': [1, 2, 4, 4], 'unet_num_heads': 8, 'unet_head_dim': 64, 'unet_res_blocks': 2, 'unet_attn_scales': [1, 0.5, 0.25], 'unet_dropout': 0.1, 'temporal_attention': 'True', 'num_timesteps': 1000, 'mean_type': 'eps', 'var_type': 'fixed_small', 'loss_type': 'mse'}}, pipeline={'type': 'latent-text-to-video-synthesis'})
device cuda
Working in txt2vid mode
  0%|                                                                                                                     | 0/1 [00:00<?, ?it/s]latents torch.Size([1, 4, 24, 32, 32]) tensor(0.0008, device='cuda:0') tensor(1.0006, device='cuda:0')
DDIM sampling tensor(1): 100%|██████████████████████████████████████████████████████████████████████████████████| 31/31 [00:43<00:00,  1.40s/it]
Traceback (most recent call last):██████████████████████████████████████████████████████████████████████████████| 31/31 [00:43<00:00,  1.30s/it]
  File "C:\Users\XXX\stable-diffusion-webui\extensions\sd-webui-modelscope-text2video\scripts\modelscope-text2vid.py", line 160, in process
    samples, _ = pipe.infer(prompt, n_prompt, steps, frames, seed + batch if seed != -1 else -1, cfg_scale,
  File "C:\Users\XXX\stable-diffusion-webui\extensions\sd-webui-modelscope-text2video\scripts\t2v_pipeline.py", line 255, in infer
    if 'CPU' in cpu_vae:
TypeError: argument of type 'NoneType' is not iterable
Exception occurred: argument of type 'NoneType' is not iterable

### WebUI and Deforum extension Commit IDs

webui commit id - 955df77
txt2vid commit id -c8335de9

### What GPU were you using for launching?

3060 -12 gb

### Settings

![image](https://user-images.githubusercontent.com/116243185/228085197-c8efb577-0492-4565-a7c9-37ee6b64ab73.png)

### Console logs

```Shell
ModelScope text2video extension for auto1111 webui
Git commit: c8335de9 (Mon Mar 27 19:49:45 2023)
Starting text2video
Pipeline setup
config namespace(framework='pytorch', task='text-to-video-synthesis', model={'type': 'latent-text-to-video-synthesis', 'model_args': {'ckpt_clip': 'open_clip_pytorch_model.bin', 'ckpt_unet': 'text2video_pytorch_model.pth', 'ckpt_autoencoder': 'VQGAN_autoencoder.pth', 'max_frames': 16, 'tiny_gpu': 1}, 'model_cfg': {'unet_in_dim': 4, 'unet_dim': 320, 'unet_y_dim': 768, 'unet_context_dim': 1024, 'unet_out_dim': 4, 'unet_dim_mult': [1, 2, 4, 4], 'unet_num_heads': 8, 'unet_head_dim': 64, 'unet_res_blocks': 2, 'unet_attn_scales': [1, 0.5, 0.25], 'unet_dropout': 0.1, 'temporal_attention': 'True', 'num_timesteps': 1000, 'mean_type': 'eps', 'var_type': 'fixed_small', 'loss_type': 'mse'}}, pipeline={'type': 'latent-text-to-video-synthesis'})
device cuda
Working in txt2vid mode
  0%|                                                                                                                     | 0/1 [00:00<?, ?it/s]latents torch.Size([1, 4, 24, 32, 32]) tensor(0.0008, device='cuda:0') tensor(1.0006, device='cuda:0')
DDIM sampling tensor(1): 100%|██████████████████████████████████████████████████████████████████████████████████| 31/31 [00:43<00:00,  1.40s/it]
Traceback (most recent call last):██████████████████████████████████████████████████████████████████████████████| 31/31 [00:43<00:00,  1.30s/it]
  File "C:\Users\xxx\stable-diffusion-webui\extensions\sd-webui-modelscope-text2video\scripts\modelscope-text2vid.py", line 160, in process
    samples, _ = pipe.infer(prompt, n_prompt, steps, frames, seed + batch if seed != -1 else -1, cfg_scale,
  File "C:\Users\xxx\stable-diffusion-webui\extensions\sd-webui-modelscope-text2video\scripts\t2v_pipeline.py", line 255, in infer
    if 'CPU' in cpu_vae:
TypeError: argument of type 'NoneType' is not iterable
Exception occurred: argument of type 'NoneType' is not iterable
```

### Additional information

Windows 10 running locally.

**Comment by hithereai** [comment]
Tried, but couldn't replicate unfortunately. 

Windows 11, same git commits as yours.

**Comment by hithereai** [comment]
How this looks at yours? 

![image](https://user-images.githubusercontent.com/121192995/228086967-46538099-d8be-4d55-9377-d3d623ff37db.png)

From webui settings -->ModelScopeTxt2Vid section.

**Comment by GrishDaProgrammer** [comment]
Same settings, GPU on half precision and not saving the model to VRAM.

**Comment by Compviztr** [comment]
Also getting the same error. Was working fine before latest update. Windows 11

**Comment by hithereai** [comment]
Mm, try to delete those 2 files from your root of webui folder:
![image](https://user-images.githubusercontent.com/121192995/228092288-6d2b5cbe-2579-4dff-93e9-35b337725403.png)


then relaunch webui and retest.

**Comment by Compviztr** [comment]
Same error after deleting above files and restarting

**Comment by Compviztr** [comment]
It works now after going to the settings and checking “keep model in VRAM…..”

**Comment by GrishDaProgrammer** [comment]
Did you make any other changes? I have made both changes and there is no change.

**Comment by GrishDaProgrammer** [comment]
> It works now after going to the settings and checking “keep model in VRAM…..”

Thanks!

The combo of removing:
config.json
ui-config.json

&

Running with Keep model in VRAM checked avoids the bug.
